version: 0.2

# env:
#   parameter-store:
#      buildNumber: "/build-number/mycodebuild"

phases:
  pre_build:
    commands:
      #- echo Logging in to Amazon ECR
      #- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo logging into docker hub
      - docker login --username csanoop50 --password "@Sanoop50"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image.
      - echo $CODEBUILD_BUILD_NUMBER
      - docker build -t image:$CODEBUILD_BUILD_NUMBER .
      - docker tag image:$CODEBUILD_BUILD_NUMBER csanoop50/test:$CODEBUILD_BUILD_NUMBER     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push csanoop50/test:$CODEBUILD_BUILD_NUMBER
